spring:
  application:
    name: task-management
  jwt:
    secret: ${JWT_SECRET}

  datasource:
    url:  ${POSTGRES_URI:jdbc:mysql://localhost:3306/task_db}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

