spring:
  application:
    name: task-management
  jwt:
    secret: ${JWT_SECRET:THHJDJKKDLDKDKDKDKDMMDKWELCOMETOTTHENEWWORLDSAMUELNAPASCO}

  datasource:
    url:  ${POSTGRES_URI:jdbc:mysql://localhost:3306/task_db}
    username: ${POSTGRES_USERNAME:root}
    password: ${POSTGRES_PASSWORD:deeplearning}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

